# This keymap requires Massdrop Configurator support
VIA_ENABLE = yes

OPT_DEFS += -DUSE_MASSDROP_CONFIGURATOR
OPT_DEFS += -DNO_PRINT
OPT_DEFS += -DNO_DEBUG

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
OPT_DEFS += -DDISABLE_LEADER

NKRO_ENABLE = yes
OPT_DEFS += -DFORCE_NKRO

COMBO_ENABLE = yes
OPT_DEFS += -DCOMBO_MUST_HOLD_MODS
